@featureTag
Feature: test feature

Scenario: this is a scenario with steps containing a data table

Given this is step 1
When I search for
  |country|Germany|
  |city|Berlin|
Then I get search results

# Generated by Cucable, Wed Sep 20 13:46:39 CEST 2017

