@featureTag
Feature: test feature

Scenario: this is a scenario with steps containing a data table

Given this is step 1
When I search for
|country|Germany|
|city||
Then I get search results from Germany

# Generated by Cucable

