Feature: test feature 2

Scenario: This is a scenario with 1 step and background

Given this is background step 1
|bg1|bg2|
And this is background step 2
Then I expect a result

# Generated by Cucable

