Feature: test feature

Scenario: This is another scenario
Given some precondition
When I do something else
Then I expect something else to happen

# Generated by Cucable, Tue Sep 05 12:58:22 CEST 2017

