@featureTag1
@featureTag2
Feature: test feature 3

@scenarioOutlineTag1
@scenarioOutlineTag2
Scenario: This is a scenario outline

Given this is step 1
|givenTable1|givenTable2|
When I search for key 1
Then I see the value 'one'
And I get some chocolate

# Generated by Cucable

