@featureTag1
@featureTag2
Feature: test feature 3

@scenarioOutlineTag1
@scenarioOutlineTag2
Scenario: This is a scenario outline

Given this is step 1
|givenTable1|givenTable2|
When I search for key 2
Then I see the value 'two'
And I get a bag of gummy bears

# Generated by Cucable

