package parallel.runners;

import cucumber.api.CucumberOptions;
import org.junit.runner.RunWith;

@CucumberOptions(
    monochrome = false,
    features = {"classpath:parallel/features/MyTest_scenario002_run001_IT.feature"},
    format = {"json:target/cucumber-report/MyTest_scenario002_run001_IT.json"},
    strict = false,
    dryRun = false
)
public class MyTest_scenario002_run001_IT {
}

// Generated by Cucable, Tue Sep 05 13:07:05 CEST 2017

