package parallel;

import cucumber.api.CucumberOptions;

@CucumberOptions(
    monochrome = false,
    features = {"classpath:parallel/features/MyTest_scenario001_run001_IT.feature"},
    format = {"json:target/cucumber-report/MyTest_scenario001_run001_IT.json"}
)
public class MyTest_scenario001_run001_IT {
}

// Generated by Cucable, Wed Sep 13 21:26:15 CEST 2017

