package parallel;

import cucumber.api.CucumberOptions;

@CucumberOptions(
    monochrome = false,
    features = {"classpath:parallel/features/MyTest1_scenario002_run001_IT.feature"},
    format = {"json:target/cucumber-report/MyTest1_scenario002_run001_IT.json"}
)
public class MyTest1_scenario002_run001_IT {
}
// Generated by Cucable

